import Head from 'next/head'
import React from 'react'
import Navbar from '../components/Navbar'
import { ExternalLinkIcon } from '@heroicons/react/solid'

const about = () => {
  return (
    <div className="text-2xl text-white">
      <Head>
        <title>Passphrase Generator</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar index={2} />

      {/* explain how passphrases work */}
      <main className="mt-20 w-full flex-1 flex-col justify-center px-20 text-center">
        <h1 className="text-6xl font-bold">What Are Passphrases?</h1>
        <p className="m-auto mt-8 max-w-2xl">
          A passphrase is a password that is lengthier than your typical
          password. They are easier to remember, and are tough to crack for a
          hacker. Passwords typically range from 8-16 characters in length, but
          passphrases can be as long as 100 characters or even more.
        </p>

        <h1 className="mt-16 text-6xl font-bold">
          How Are Passphrases Generated?
        </h1>
        <p className="m-auto mt-8 max-w-2xl">
          Passphrases are generated by combining words from a dictionary called
          diceware. Diceware is list of words where each word corresponds with a
          specific and unique number. This number represents the 6 dice you have
          "roll" to get that word. For example, in the english diceware list,
          424242 corresponds with the word mite. When the passphrase is
          generated, multiple digital dice are rolled to generate the
          passphrase. For more information about diceware, check out{' '}
          <a
            href="https://en.wikipedia.org/wiki/Diceware"
            className=" text-blue-300 hover:underline"
          >
            Wikipedia
            <ExternalLinkIcon className="ml-1 inline h-6 w-6" />
          </a>
        </p>
      </main>
    </div>
  )
}

export default about
